# Generated by Django 3.0.2 on 2020-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='photos/noimg.png', upload_to='photos/%Y'),
        ),
        migrations.AlterField(
            model_name='author',
            name='intro',
            field=models.TextField(),
        ),
    ]
